"use client";

import { useState } from "react";
import {
  Gift,
  IndianRupee,
  Copy,
  Check,
  Share2,
  Wallet,
  MessageCircle,
} from "lucide-react";

import { useReferral } from "@/features/parent/hooks/useReferral";
import ErrorBanner from "@/features/shared/components/ErrorBanner";

/**
 * "Referral" sidebar entry — previously a placeholder link with no
 * page behind it (ParentSidebar.tsx already pointed here). Shows the
 * Parent's own shareable code (`ParentProfile.referralCode`, lazily
 * generated by GET /api/parent/referral -> getReferralSummaryForParent),
 * a copy/share action, and the status of every referral they've made.
 *
 * Reward timing (per direct instruction, Sep 8, 2026): the referrer
 * is paid ₹500 to their Wallet only once the referred Parent
 * *successfully enrolls* in a course — never before that, and never
 * just for signing up with a code. See
 * `processReferralRewardForNewEnrollment()` in `referral.service.ts`.
 */

const currency = new Intl.NumberFormat("en-IN", {
  style: "currency",
  currency: "INR",
  maximumFractionDigits: 0,
});

function refereeName(r: { firstName: string; lastName: string; visibleName: string | null }) {
  return r.visibleName?.trim() || `${r.firstName} ${r.lastName}`.trim();
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export default function ParentReferralPage() {
  const { summary, loading, error } = useReferral();
  const [copied, setCopied] = useState(false);

  const shareText = summary
    ? `Join Learniee using my referral code ${summary.code} and get started with quality 1-on-1 online classes! Sign up at https://learniee.com and enter this code during onboarding.`
    : "";

  async function handleCopy() {
    if (!summary) return;

    try {
      await navigator.clipboard.writeText(summary.code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API can fail silently (permissions, non-secure
      // context) — the code is still visible on screen to copy by hand.
    }
  }

  return (
    <div className="p-6 max-w-3xl mx-auto">
      {/* Hero */}
      <div className="mb-6">
        <div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-600 bg-violet-100 px-3 py-1 rounded-full mb-3">
          <Gift size={14} />
          Refer &amp; Earn
        </div>
        <h1 className="text-2xl font-bold text-violet-900">
          Share learning. Earn rewards.
        </h1>
        <p className="text-gray-500 mt-2">
          Share your code with anyone looking for quality online classes.
          You earn {summary ? currency.format(summary.rewardAmount) : "₹500"}{" "}
          once they successfully enroll in a course — not before.
        </p>
      </div>

      {error && (
        <ErrorBanner>{error}</ErrorBanner>
      )}

      {/* Your code */}
      <div className="bg-violet-900 text-white rounded-2xl p-6 mb-6">
        <p className="text-sm text-white/70 mb-2">Your referral code</p>

        {loading ? (
          <div className="h-10 w-40 rounded-lg bg-white/10 animate-pulse" />
        ) : (
          <div className="flex items-center gap-3 flex-wrap">
            <span className="font-mono text-3xl font-bold tracking-widest">
              {summary?.code}
            </span>
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 bg-white/15 hover:bg-white/25 text-sm font-semibold px-3 py-1.5 rounded-lg"
            >
              {copied ? <Check size={15} /> : <Copy size={15} />}
              {copied ? "Copied" : "Copy"}
            </button>
          </div>
        )}

        <p className="text-white/70 text-sm mt-3">
          They enter this code during sign-up. No limit on how many people
          you can refer.
        </p>

        {summary && (
          <a
            href={`https://wa.me/?text=${encodeURIComponent(shareText)}`}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold px-4 py-2.5 rounded-lg mt-4"
          >
            <Share2 size={16} />
            Share on WhatsApp
          </a>
        )}
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <div className="bg-white border rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-2 text-gray-500 text-xs font-semibold uppercase mb-1">
            <IndianRupee size={14} />
            Total earned
          </div>
          <p className="text-2xl font-bold text-green-700">
            {loading ? "…" : currency.format(summary?.totalEarned ?? 0)}
          </p>
        </div>
        <div className="bg-white border rounded-xl p-5 shadow-sm">
          <div className="flex items-center gap-2 text-gray-500 text-xs font-semibold uppercase mb-1">
            <Gift size={14} />
            Awaiting enrollment
          </div>
          <p className="text-2xl font-bold text-amber-600">
            {loading ? "…" : summary?.pendingCount ?? 0}
          </p>
        </div>
      </div>

      {/* Referral list */}
      <div className="mb-6">
        <h2 className="font-semibold text-gray-800 mb-3">Your referrals</h2>

        {loading ? (
          <div className="space-y-3">
            {[...Array(2)].map((_, i) => (
              <div key={i} className="h-16 rounded-xl bg-violet-50 animate-pulse" />
            ))}
          </div>
        ) : !summary || summary.referrals.length === 0 ? (
          <div className="bg-white border-2 border-dashed border-violet-200 rounded-xl p-8 text-center">
            <p className="text-gray-500">
              No referrals yet — share your code above to get started.
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {summary.referrals.map((r) => (
              <div
                key={r.id}
                className="bg-white border rounded-xl p-4 shadow-sm flex items-center justify-between gap-3"
              >
                <div>
                  <p className="font-semibold text-gray-800">{refereeName(r.referee)}</p>
                  <p className="text-xs text-gray-400">
                    Referred {formatDate(r.createdAt)}
                    {r.rewardedAt && ` · Rewarded ${formatDate(r.rewardedAt)}`}
                  </p>
                </div>
                <span
                  className={`text-xs font-bold px-3 py-1 rounded-full whitespace-nowrap ${
                    r.status === "REWARDED"
                      ? "bg-green-100 text-green-700"
                      : "bg-amber-100 text-amber-700"
                  }`}
                >
                  {r.status === "REWARDED"
                    ? `+${currency.format(Number(r.rewardAmount))}`
                    : "Awaiting enrollment"}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* How it works */}
      <div className="bg-white border rounded-xl p-5 shadow-sm mb-6">
        <h2 className="font-semibold text-gray-800 mb-4">How it works</h2>

        <ol className="space-y-4">
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-violet-100 text-violet-700 text-xs font-bold flex items-center justify-center flex-shrink-0">
              1
            </span>
            <p className="text-sm text-gray-600">
              Share your code with anyone looking for quality 1-on-1 or
              small-group online classes.
            </p>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-violet-100 text-violet-700 text-xs font-bold flex items-center justify-center flex-shrink-0">
              2
            </span>
            <p className="text-sm text-gray-600">
              They enter it while signing up, then go on to successfully
              enroll and pay for a course.
            </p>
          </li>
          <li className="flex gap-3">
            <span className="w-6 h-6 rounded-full bg-violet-100 text-violet-700 text-xs font-bold flex items-center justify-center flex-shrink-0">
              3
            </span>
            <p className="text-sm text-gray-600">
              The moment that enrollment goes through,{" "}
              {summary ? currency.format(summary.rewardAmount) : "₹500"} lands
              directly in your Learniee Wallet — automatically, no waiting on
              support.
            </p>
          </li>
        </ol>
      </div>

      <div className="bg-green-50 border border-green-100 rounded-xl p-5 mb-6 flex gap-3">
        <Wallet size={20} className="text-green-700 flex-shrink-0 mt-0.5" />
        <p className="text-sm text-green-700/90">
          Rewards are credited straight to your Wallet, not your original
          payment method — you can see every credit in{" "}
          <a href="/parent/wallet" className="font-semibold underline">
            Wallet
          </a>
          .
        </p>
      </div>

      <div className="bg-white border rounded-xl p-5 shadow-sm flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h2 className="font-semibold text-gray-800">Need help referring someone?</h2>
          <p className="text-sm text-gray-500 mt-1">Reach out to us directly.</p>
        </div>
        <a
          href="https://wa.me/919833077682"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm font-semibold px-4 py-2.5 rounded-lg whitespace-nowrap"
        >
          <MessageCircle size={16} />
          WhatsApp us
        </a>
      </div>
    </div>
  );
}
